language: go

go:
  - "1.13.x"

go_import_path: github.com/corestario/kyber

script: GO111MODULE=on make test

notifications:
  email: false

# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
